/*
 * BooConnecctLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package run.booconnect;

import run.booconnect.controllers.*;
import run.booconnect.http.client.HttpClient;

public class BooConnecctClient {
    /**
     * Singleton access to VerifyPhoneVerificationEndpoints controller
     * @return	Returns the VerifyPhoneVerificationEndpointsController instance 
     */
    public VerifyPhoneVerificationEndpointsController getVerifyPhoneVerificationEndpoints() {
        return VerifyPhoneVerificationEndpointsController.getInstance();
    }

    /**
     * Singleton access to ResturantListsResturantsRegisteredOnBooconnect controller
     * @return	Returns the ResturantListsResturantsRegisteredOnBooconnectController instance 
     */
    public ResturantListsResturantsRegisteredOnBooconnectController getResturantListsResturantsRegisteredOnBooconnect() {
        return ResturantListsResturantsRegisteredOnBooconnectController.getInstance();
    }

    /**
     * Singleton access to OrdersOrdersResourceEndpoints controller
     * @return	Returns the OrdersOrdersResourceEndpointsController instance 
     */
    public OrdersOrdersResourceEndpointsController getOrdersOrdersResourceEndpoints() {
        return OrdersOrdersResourceEndpointsController.getInstance();
    }

    /**
     * Singleton access to ItemsItemsSoldInResturantsRegisteredOnBooConnect controller
     * @return	Returns the ItemsItemsSoldInResturantsRegisteredOnBooConnectController instance 
     */
    public ItemsItemsSoldInResturantsRegisteredOnBooConnectController getItemsItemsSoldInResturantsRegisteredOnBooConnect() {
        return ItemsItemsSoldInResturantsRegisteredOnBooConnectController.getInstance();
    }

    /**
     * Singleton access to CheckoutCheckoutResourceEndpoints controller
     * @return	Returns the CheckoutCheckoutResourceEndpointsController instance 
     */
    public CheckoutCheckoutResourceEndpointsController getCheckoutCheckoutResourceEndpoints() {
        return CheckoutCheckoutResourceEndpointsController.getInstance();
    }

    /**
     * Singleton access to CartShoppingCartEndpoints controller
     * @return	Returns the CartShoppingCartEndpointsController instance 
     */
    public CartShoppingCartEndpointsController getCartShoppingCartEndpoints() {
        return CartShoppingCartEndpointsController.getInstance();
    }

    /**
     * Singleton access to AccountAccountEndpoints controller
     * @return	Returns the AccountAccountEndpointsController instance 
     */
    public AccountAccountEndpointsController getAccountAccountEndpoints() {
        return AccountAccountEndpointsController.getInstance();
    }

    /**
     * Singleton access to WishlistItemWishlistResourceEndpoints controller
     * @return	Returns the WishlistItemWishlistResourceEndpointsController instance 
     */
    public WishlistItemWishlistResourceEndpointsController getWishlistItemWishlistResourceEndpoints() {
        return WishlistItemWishlistResourceEndpointsController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public BooConnecctClient() {
    }

}